Feature/lock unlock actions
scm-manager/scm-file-lock-plugin pull request #3
Opened 2021-10-28 07:00 UTC by eheimbuch

## Proposed changes

Add lock and unlock action to source view and file content view. If a file is locked it can only be edited by the locking user. But every user is free to remove this lock and edit it again. Also show a warn modal if a user tries to upload and overwrite a locked file.

### Your checklist for this pull request

**Contributor**:
- [x] PR is well described and the description can be used as a commit message on squash
- [x] Related issues linked to PR if existing and labels set
- [x] New code is covered with unit tests
- [ ] New ui components are tested inside the storybook (module ui-components only) 
- [x] [Changelog entry file](https://github.com/scm-manager/changelog#changelog-entry-files) created in `gradle/changelog` or CHANGELOG.md is updated for plugins
- [x] Feature has been tested with different permissions
- [x] Documentation updated (only necessary for new features or changed behaviour)

**Reviewer**:
- [ ] The clean code principles are respected ([CleanCode](https://clean-code-developer.com/virtues/))
- [ ] All new code/logic is implemented on the right spot / "Should this be done here?"
- [ ] UI changes fits into the layout
- [ ] The UI views / components are responsive (mobile views)
- [ ] Correct translations are available

### Checklist for branch merge request (not required for forks)

- [ ] Branch is green/blue on [Jenkins](https://oss.cloudogu.com/jenkins/)
- [ ] Quality Gate passed on [SonarQube](https://sonarcloud.io/organizations/scm-manager/projects)

2021-11-01 14:46 UTC, sdorra requested changes

2021-11-01 14:46 UTC, sdorra commented on src/main/js/FileLockUploadModal.tsx
> +      for (let lock of data?._embedded?.fileLocks as FileLock[]) {
Iterate over possible undefined?

2021-11-01 14:46 UTC, sdorra commented on src/main/java/com/cloudogu/filelock/FileLockMapper.java
> +    dto.setWriteAccess(fileLock.getUserId().equals(username));
I would prefer something like `owned` instead of `writeAccess`

2021-11-02 06:36 UTC, sdorra commented
The tooltip for a file locked by the current user is misleading. Something like `locked by you at time` would be things more clear.

2021-11-02 06:37 UTC, sdorra commented
The download icon has no cursor pointer.

2021-11-02 06:39 UTC, sdorra commented
I think the yellow tooltip should describe, that the lock is steeled by clicking the icon.

2021-11-02 06:44 UTC, sdorra commented
Wouldn't it be better to remove the file from the upload table after clicking cancel in the upload lock conflict dialog?

2021-11-02 06:44 UTC, sdorra commented
Was the download unlock dialog removed?

2021-11-02 08:36 UTC, eheimbuch commented
> Wouldn't it be better to remove the file from the upload table after clicking cancel in the upload lock conflict dialog?

And if i select like 10 files? Do i only "reject" the locked ones and keep the unlocked files?

2021-11-02 08:45 UTC, eheimbuch commented
> Was the download unlock dialog removed?

Works for me. The lock modal only appears if you download unlocked files.

2021-11-02 08:46 UTC, eheimbuch commented
> I think the yellow tooltip should describe, that the lock is steeled by clicking the icon and the green one should say that the file is unlocked after clicking.

Both clicks just unlocks the file. But i will add it :+1:

2021-11-02 15:01 UTC, merged